### ISSUE TITLE
release v1.3 TODO

### ISSUE THREAD

**Issue by Ark2000** [Ark2000/PankuConsole#62]
- [x] Finish all existing 1.3 Milestone issues.
- [x] Update docs, with Chinese version.
- [ ] A live demo web page with basic instructions.
- [ ] A youtube video explaining all available features.
